version: '2'

services:

  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - clientescrud
      - productoscrud

  clientescrud:
    build: ./clientescrud
  
  productoscrud:
    build: ./productoscrud
  